* Test 19

diff --git a/.github/workflows/maven-release.yml b/.github/workflows/maven-release.yml
--- a/.github/workflows/maven-release.yml
+++ b/.github/workflows/maven-release.yml
@@ -91,163 +91,194 @@ jobs:
         git tag -d ${{ env.tagName }} || true
         git push origin :refs/tags/${{ env.tagName }} || true
 
-  prepare-os-release:
-    name:  Prepare Release v${{ inputs.releaseVersion }} on ${{ matrix.os }}
-
-    needs: prepare
-
-    runs-on: ${{ matrix.os }}
-
-    strategy:
-      matrix:
-        os: [ ubuntu-latest, windows-latest ]
-
-    steps:
-    - uses: actions/checkout@v4
-    
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: "17"
-        distribution: temurin
-        java-package: jdk
-        cache: maven
-        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
-        settings-path: ${{ github.workspace }} # location for the settings.xml file
-
-    - name: Configure Git User
+    - name: Update project version to ${{ inputs.releaseVersion }}
       run: |
-        git config user.email "actions@github.com"
-        git config user.name "GitHub Actions"
-
-    - name: Set release branch and tag name
-      run: |
-        echo "branchName=release/v$INPUT_RELEASEVERSION" >> $GITHUB_ENV
-        echo "tagName=v$INPUT_RELEASEVERSION" >> $GITHUB_ENV
-      env:
-        INPUT_RELEASEVERSION: ${{ inputs.releaseVersion }}
-
-    - name: Checkout ${{ env.branchName }} branch
-      run: |
-        git fetch
-        git checkout ${{ env.branchName }} 2>/dev/null
-
-    - name: Prepare release
-      id: prepare
-      run: |
-        mvn -B -U \
-          release:clean \
-          release:prepare \
-          -DpreparationGoals="clean verify" \
-          -DreleaseVersion=${{ inputs.releaseVersion }} \
-          -DdevelopmentVersion=${{ inputs.developmentVersion }} \
-          -Dresume=false
+        mvn versions:set -DnewVersion=${{ inputs.releaseVersion }}
+        mvn versions:commit
+        git add *.pom.xml
+        git commit -m "Updated POM version to ${{ inputs.releaseVersion }}"
       env:
         GITHUB_TOKEN: ${{ github.token }}
 
-    - name: Release rollback on failure
+    - name: Create tag ${{ env.tagName }}
       run: |
-        mvn -B -U \
-          release:rollback \
-      if: always() && (steps.prepare.outcome == 'failure')
-    
-    - uses: actions/upload-artifact@v4
-      with:
-        name: release-${{ matrix.os }}.properties
-        path: release.properties
+        git tag -a ${{ env.tagName }} -m "Release ${{ env.tagName }}"
 
-  release:
-    name: Release v${{ inputs.releaseVersion }} on ${{ matrix.os }}
-
-    needs: prepare-os-release
-
-    runs-on: ${{ matrix.os }}
-
-    strategy:
-      matrix:
-        os: [ ubuntu-latest, windows-latest ]
-    
-    steps:
-
-    - uses: actions/checkout@v4
-    
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: "17"
-        distribution: temurin
-        java-package: jdk
-        cache: maven
-        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
-        settings-path: ${{ github.workspace }} # location for the settings.xml file
-
-    - uses: actions/download-artifact@v4
-      with:
-        name: release-${{ matrix.os }}.properties
-
-    - name: Perform release to GitHub Packages
-      id: perform
+    - name: Push tag ${{ env.tagName }}
       run: |
-        mvn -B -U \
-          release:perform \
-          -Dgoals=deploy \
-          -DworkingDirectory=$GITHUB_WORKSPACE/target/release \
-          -DreleaseVersion=${{ inputs.releaseVersion }} \
-          -DdevelopmentVersion=${{ inputs.developmentVersion }} \
-          -s $GITHUB_WORKSPACE/settings.xml
+        git push origin ${{ env.branchName }}
+
+    - name: Prepare next version ${{ inputs.developmentVersion }}
+      run: |
+        mvn versions:set -DnewVersion=${{ inputs.developmentVersion }}
+        mvn versions:commit
+        git add *.pom.xml
+        git commit -m "Updated POM version to ${{ inputs.developmentVersion }}"
       env:
         GITHUB_TOKEN: ${{ github.token }}
 
-    - name: Release rollback on failure
+    - name: Push next version ${{ inputs.developmentVersion }}"
       run: |
-        mvn -B -U \
-          release:rollback \
-      if: always() && (steps.perform.outcome == 'failure')
+        git push origin ${{ env.branchName }}
 
-    - uses: actions/upload-artifact@v4
-      with:
-        name: jre-${{ matrix.os }}
-        path: |
-          ./target/release/target/*.buildinfo
-          ./target/release/metricshub-jre-*/target/*.zip
-          ./target/release/metricshub-jre-*/target/*.buildinfo
 
-  # Finalize job
-  finalize:
-    name: Finalize release
-    runs-on: ubuntu-latest
-    needs: [ prepare, prepare-os-release, release ]
-    steps:
+  # prepare-os-release:
+  #   name:  Prepare Release v${{ inputs.releaseVersion }} on ${{ matrix.os }}
 
-    - uses: actions/checkout@v4
+  #   needs: prepare
 
-    - uses: actions/download-artifact@v4
-      with:
-        merge-multiple: true
+  #   runs-on: ${{ matrix.os }}
 
-    - name: Create a GitHub Release
-      uses: softprops/action-gh-release@v1
-      with:
-        tag_name: ${{ needs.prepare.outputs.tagName }}
-        fail_on_unmatched_files: false
-        generate_release_notes: true
-        files: |
-          ./target/*.buildinfo
-          ./metricshub-jre-*/target/*.zip
-          ./metricshub-jre-*/target/*.buildinfo
+  #   strategy:
+  #     matrix:
+  #       os: [ ubuntu-latest, windows-latest ]
 
-    - name: Create Pull Request from ${{ needs.prepare.outputs.branchName }} to ${{ github.event.repository.default_branch }}
-      uses: devops-infra/action-pull-request@v0.5.5
-      with:
-        github_token: ${{ github.token }}
-        source_branch: ${{ needs.prepare.outputs.branchName }}
-        target_branch: ${{ github.event.repository.default_branch }}
-        title: Release v${{ inputs.releaseVersion }} and prepare v${{ inputs.developmentVersion }}
-        body: |
-          ## Automated release
+  #   steps:
+  #   - uses: actions/checkout@v4
+    
+  #   - name: Set up JDK 17
+  #     uses: actions/setup-java@v4
+  #     with:
+  #       java-version: "17"
+  #       distribution: temurin
+  #       java-package: jdk
+  #       cache: maven
+  #       server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
+  #       settings-path: ${{ github.workspace }} # location for the settings.xml file
+
+  #   - name: Configure Git User
+  #     run: |
+  #       git config user.email "actions@github.com"
+  #       git config user.name "GitHub Actions"
+
+  #   - name: Set release branch and tag name
+  #     run: |
+  #       echo "branchName=release/v$INPUT_RELEASEVERSION" >> $GITHUB_ENV
+  #       echo "tagName=v$INPUT_RELEASEVERSION" >> $GITHUB_ENV
+  #     env:
+  #       INPUT_RELEASEVERSION: ${{ inputs.releaseVersion }}
+
+  #   - name: Checkout ${{ env.branchName }} branch
+  #     run: |
+  #       git fetch
+  #       git checkout ${{ env.branchName }} 2>/dev/null
+
+  #   - name: Prepare release
+  #     id: prepare
+  #     run: |
+  #       mvn -B -U \
+  #         release:clean \
+  #         release:prepare \
+  #         -DpreparationGoals="clean verify" \
+  #         -DreleaseVersion=${{ inputs.releaseVersion }} \
+  #         -DdevelopmentVersion=${{ inputs.developmentVersion }} \
+  #         -Dresume=false
+  #     env:
+  #       GITHUB_TOKEN: ${{ github.token }}
+
+  #   - name: Release rollback on failure
+  #     run: |
+  #       mvn -B -U \
+  #         release:rollback \
+  #     if: always() && (steps.prepare.outcome == 'failure')
+    
+  #   - uses: actions/upload-artifact@v4
+  #     with:
+  #       name: release-${{ matrix.os }}.properties
+  #       path: release.properties
+
+  # release:
+  #   name: Release v${{ inputs.releaseVersion }} on ${{ matrix.os }}
+
+  #   needs: prepare-os-release
+
+  #   runs-on: ${{ matrix.os }}
+
+  #   strategy:
+  #     matrix:
+  #       os: [ ubuntu-latest, windows-latest ]
+    
+  #   steps:
+
+  #   - uses: actions/checkout@v4
+    
+  #   - name: Set up JDK 17
+  #     uses: actions/setup-java@v4
+  #     with:
+  #       java-version: "17"
+  #       distribution: temurin
+  #       java-package: jdk
+  #       cache: maven
+  #       server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
+  #       settings-path: ${{ github.workspace }} # location for the settings.xml file
+
+  #   - uses: actions/download-artifact@v4
+  #     with:
+  #       name: release-${{ matrix.os }}.properties
+
+  #   - name: Perform release to GitHub Packages
+  #     id: perform
+  #     run: |
+  #       mvn -B -U \
+  #         release:perform \
+  #         -Dgoals=deploy \
+  #         -DworkingDirectory=$GITHUB_WORKSPACE/target/release \
+  #         -DreleaseVersion=${{ inputs.releaseVersion }} \
+  #         -DdevelopmentVersion=${{ inputs.developmentVersion }} \
+  #         -s $GITHUB_WORKSPACE/settings.xml
+  #     env:
+  #       GITHUB_TOKEN: ${{ github.token }}
+
+  #   - name: Release rollback on failure
+  #     run: |
+  #       mvn -B -U \
+  #         release:rollback \
+  #     if: always() && (steps.perform.outcome == 'failure')
+
+  #   - uses: actions/upload-artifact@v4
+  #     with:
+  #       name: jre-${{ matrix.os }}
+  #       path: |
+  #         ./target/release/target/*.buildinfo
+  #         ./target/release/metricshub-jre-*/target/*.zip
+  #         ./target/release/metricshub-jre-*/target/*.buildinfo
+
+  # # Finalize job
+  # finalize:
+  #   name: Finalize release
+  #   runs-on: ubuntu-latest
+  #   needs: [ prepare, prepare-os-release, release ]
+  #   steps:
+
+  #   - uses: actions/checkout@v4
+
+  #   - uses: actions/download-artifact@v4
+  #     with:
+  #       merge-multiple: true
+
+  #   - name: Create a GitHub Release
+  #     uses: softprops/action-gh-release@v1
+  #     with:
+  #       tag_name: ${{ needs.prepare.outputs.tagName }}
+  #       fail_on_unmatched_files: false
+  #       generate_release_notes: true
+  #       files: |
+  #         ./target/*.buildinfo
+  #         ./metricshub-jre-*/target/*.zip
+  #         ./metricshub-jre-*/target/*.buildinfo
+
+  #   - name: Create Pull Request from ${{ needs.prepare.outputs.branchName }} to ${{ github.event.repository.default_branch }}
+  #     uses: devops-infra/action-pull-request@v0.5.5
+  #     with:
+  #       github_token: ${{ github.token }}
+  #       source_branch: ${{ needs.prepare.outputs.branchName }}
+  #       target_branch: ${{ github.event.repository.default_branch }}
+  #       title: Release v${{ inputs.releaseVersion }} and prepare v${{ inputs.developmentVersion }}
+  #       body: |
+  #         ## Automated release
           
-          * Release **v${{ inputs.releaseVersion }}**
-          * Prepare **v${{ inputs.developmentVersion }}**
-        label: automatic
-        get_diff: true
-        allow_no_diff: true
+  #         * Release **v${{ inputs.releaseVersion }}**
+  #         * Prepare **v${{ inputs.developmentVersion }}**
+  #       label: automatic
+  #       get_diff: true
+  #       allow_no_diff: true
